services:
  - type: web
    name: dividanselo-backend
    runtime: node
    rootDir: server
    buildCommand: npm install --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
